[build]

functions = "functions"
publish = "dist"



[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
  
 [[redirects]]
  from = "/.netlify/functions/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
