[build]

functions = "functions"
publish = "this"

[[redirects]]

status = 200
headers = { Access-Control-Allow-Origin = “*”}


[headers.values]
Access-Control-Allow-Origin = “**”


[[headers]]
Define which paths this specific [[headers]] block will cover.
for = “/api/*”
[headers.values]
Access-Control-Allow-Origin = “**”


